# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uidemo1.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UIDemo1(object):
    def setupUi(self, UIDemo1):
        UIDemo1.setObjectName("UIDemo1")
        UIDemo1.resize(800, 600)
        UIDemo1.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(UIDemo1)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetTitle = QtWidgets.QWidget(UIDemo1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetTitle.sizePolicy().hasHeightForWidth())
        self.widgetTitle.setSizePolicy(sizePolicy)
        self.widgetTitle.setObjectName("widgetTitle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetTitle)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labIco = QtWidgets.QLabel(self.widgetTitle)
        self.labIco.setText("")
        self.labIco.setAlignment(QtCore.Qt.AlignCenter)
        self.labIco.setObjectName("labIco")
        self.horizontalLayout_2.addWidget(self.labIco)
        self.labTitle = QtWidgets.QLabel(self.widgetTitle)
        self.labTitle.setStyleSheet("")
        self.labTitle.setText("")
        self.labTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labTitle.setObjectName("labTitle")
        self.horizontalLayout_2.addWidget(self.labTitle)
        self.widgetTop = QtWidgets.QWidget(self.widgetTitle)
        self.widgetTop.setObjectName("widgetTop")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetTop)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnMain = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMain.sizePolicy().hasHeightForWidth())
        self.btnMain.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/demo/main_main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMain.setIcon(icon)
        self.btnMain.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnMain.setObjectName("btnMain")
        self.horizontalLayout_3.addWidget(self.btnMain)
        self.btnConfig = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfig.sizePolicy().hasHeightForWidth())
        self.btnConfig.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/demo/main_config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfig.setIcon(icon1)
        self.btnConfig.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_3.addWidget(self.btnConfig)
        self.btnData = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnData.sizePolicy().hasHeightForWidth())
        self.btnData.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/demo/main_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnData.setIcon(icon2)
        self.btnData.setChecked(False)
        self.btnData.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnData.setObjectName("btnData")
        self.horizontalLayout_3.addWidget(self.btnData)
        self.btnHelp = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHelp.sizePolicy().hasHeightForWidth())
        self.btnHelp.setSizePolicy(sizePolicy)
        self.btnHelp.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/demo/main_help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon3)
        self.btnHelp.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout_3.addWidget(self.btnHelp)
        self.btnExit = QtWidgets.QToolButton(self.widgetTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/demo/main_exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon4)
        self.btnExit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_3.addWidget(self.btnExit)
        self.horizontalLayout_2.addWidget(self.widgetTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widgetMenu = QtWidgets.QWidget(self.widgetTitle)
        self.widgetMenu.setObjectName("widgetMenu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetMenu)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 3)
        self.btnMenu_Min = QtWidgets.QPushButton(self.widgetMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Min.sizePolicy().hasHeightForWidth())
        self.btnMenu_Min.setSizePolicy(sizePolicy)
        self.btnMenu_Min.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMenu_Min.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Min.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Min.setText("")
        self.btnMenu_Min.setObjectName("btnMenu_Min")
        self.gridLayout_2.addWidget(self.btnMenu_Min, 0, 1, 1, 1)
        self.btnMenu_Close = QtWidgets.QPushButton(self.widgetMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Close.sizePolicy().hasHeightForWidth())
        self.btnMenu_Close.setSizePolicy(sizePolicy)
        self.btnMenu_Close.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMenu_Close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnMenu_Close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Close.setText("")
        self.btnMenu_Close.setObjectName("btnMenu_Close")
        self.gridLayout_2.addWidget(self.btnMenu_Close, 0, 3, 1, 1)
        self.btnMenu_Max = QtWidgets.QPushButton(self.widgetMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMenu_Max.sizePolicy().hasHeightForWidth())
        self.btnMenu_Max.setSizePolicy(sizePolicy)
        self.btnMenu_Max.setMinimumSize(QtCore.QSize(30, 30))
        self.btnMenu_Max.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMenu_Max.setText("")
        self.btnMenu_Max.setObjectName("btnMenu_Max")
        self.gridLayout_2.addWidget(self.btnMenu_Max, 0, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.widgetMenu)
        self.verticalLayout.addWidget(self.widgetTitle)
        self.stackedWidget = QtWidgets.QStackedWidget(UIDemo1)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lab1 = QtWidgets.QLabel(self.page1)
        self.lab1.setStyleSheet("")
        self.lab1.setAlignment(QtCore.Qt.AlignCenter)
        self.lab1.setObjectName("lab1")
        self.verticalLayout_2.addWidget(self.lab1)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lab2 = QtWidgets.QLabel(self.page2)
        self.lab2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab2.setObjectName("lab2")
        self.verticalLayout_3.addWidget(self.lab2)
        self.stackedWidget.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lab3 = QtWidgets.QLabel(self.page3)
        self.lab3.setAlignment(QtCore.Qt.AlignCenter)
        self.lab3.setObjectName("lab3")
        self.verticalLayout_5.addWidget(self.lab3)
        self.stackedWidget.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lab4 = QtWidgets.QLabel(self.page4)
        self.lab4.setAlignment(QtCore.Qt.AlignCenter)
        self.lab4.setObjectName("lab4")
        self.verticalLayout_4.addWidget(self.lab4)
        self.stackedWidget.addWidget(self.page4)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(UIDemo1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UIDemo1)

    def retranslateUi(self, UIDemo1):
        _translate = QtCore.QCoreApplication.translate
        UIDemo1.setWindowTitle(_translate("UIDemo1", "Form"))
        self.btnMain.setText(_translate("UIDemo1", "主界面"))
        self.btnConfig.setText(_translate("UIDemo1", "系统设置"))
        self.btnData.setText(_translate("UIDemo1", "警情查询"))
        self.btnHelp.setText(_translate("UIDemo1", "调试帮助"))
        self.btnExit.setText(_translate("UIDemo1", "用户退出"))
        self.btnMenu_Min.setToolTip(_translate("UIDemo1", "最小化"))
        self.btnMenu_Close.setToolTip(_translate("UIDemo1", "关闭"))
        self.lab1.setText(_translate("UIDemo1", "主界面"))
        self.lab2.setText(_translate("UIDemo1", "系统设置"))
        self.lab3.setText(_translate("UIDemo1", "警情查询"))
        self.lab4.setText(_translate("UIDemo1", "调试帮助"))


